### ISSUE TITLE
Failed to launch the browser process

### ISSUE THREAD

**Issue by Kujo-Jotaro-AAAAA** [rrweb-io/rrvideo#15]
MAC OS
run: 
rrvideo --input ./src/files/rrweb.json

error message:

Failed to transform this session.
Error: Failed to launch the browser process!

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/rrvideo/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/usr/local/lib/node_modules/rrvideo/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1218:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by zyktrcn** [comment]
You can change the path in puppeteer
```javascript
// xxx(your rrvideo path)/node_modules/puppeteer/lib/cjs/puppteer/node/Launcher.js
// before
let chromeExecutable = executablePath;
if (os.arch() === 'arm64') {
    chromeExecutable = '/usr/bin/chromium-browser';
}

// after
let chromeExecutable = executablePath;
if (os.arch() === 'arm64') {
    chromeExecutable = '/Applications/Chromium.app/Contents/MacOS/Chromium';
}
```
[relation](https://github.com/puppeteer/puppeteer/issues/5662#issuecomment-891297815)
