### ISSUE TITLE
运行rrvideo报错：Failed to launch the browser process

### ISSUE THREAD

**Issue by liuzx1337** [rrweb-io/rrvideo#7]
按步骤安装后，运行rrvideo --input path --output path 后，报如下错误：

`Failed to transform this session.
Error: Failed to launch the browser process!
[1228/153652.232185:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x55b254094b39 base::debug::CollectStackTrace()
#1 0x55b2540074c3 base::debug::StackTrace::StackTrace()
#2 0x55b254017c80 logging::LogMessage::~LogMessage()
#3 0x55b252aa9f5e content::ZygoteHostImpl::Init()
#4 0x55b253fb1cf8 content::ContentMainRunnerImpl::Initialize()
#5 0x55b253fafe0b content::RunContentProcess()
#6 0x55b253faff5c content::ContentMain()
#7 0x55b2540013d2 headless::(anonymous namespace)::RunContentMain()
#8 0x55b2540010bc headless::HeadlessShellMain()
#9 0x55b251602a03 ChromeMain
#10 0x7f20fe570495 __libc_start_main
#11 0x55b25160282a _start

Received signal 6
#0 0x55b254094b39 base::debug::CollectStackTrace()
#1 0x55b2540074c3 base::debug::StackTrace::StackTrace()
#2 0x55b2540946db base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f2103f025d0 (/usr/lib64/libpthread-2.17.so+0xf5cf)
#4 0x7f20fe5842c7 __GI_raise
#5 0x7f20fe5859b8 __GI_abort
#6 0x55b254093665 base::debug::BreakDebugger()
#7 0x55b2540180f2 logging::LogMessage::~LogMessage()
#8 0x55b252aa9f5e content::ZygoteHostImpl::Init()
#9 0x55b253fb1cf8 content::ContentMainRunnerImpl::Initialize()
#10 0x55b253fafe0b content::RunContentProcess()
#11 0x55b253faff5c content::ContentMain()
#12 0x55b2540013d2 headless::(anonymous namespace)::RunContentMain()
#13 0x55b2540010bc headless::HeadlessShellMain()
#14 0x55b251602a03 ChromeMain
#15 0x7f20fe570495 __libc_start_main
#16 0x55b25160282a _start
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000008 r11: 0000000000000202
 r12: 00007ffc03735520 r13: aaaaaaaaaaaaaaaa r14: 00007ffc03735530 r15: 00007ffc03734cb0
  di: 0000000000005c57  si: 0000000000005c57  bp: 00007ffc03734460  bx: 00007ffc03734cd0
  dx: 0000000000000006  ax: 0000000000000000  cx: ffffffffffffffff  sp: 00007ffc03734328
  ip: 00007f20fe5842c7 efl: 0000000000000202 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/opt/ebiz/node-v12.18.3-linux-x64/lib/node_modules/rrvideo/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/opt/ebiz/node-v12.18.3-linux-x64/lib/node_modules/rrvideo/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
`

**Comment by yuezhenyu0208** [comment]
你修复此问题了么？我现在也遇到这个问题了

**Comment by Kujo-Jotaro-AAAAA** [comment]
+1
